export const cameraData = [
  {
    id: 1,
    name: "Camera 1",
    health: "Good",
    location: "New York, NY",
    recorder: "NY Recorder",
    tasks: "3 Tasks",
    status: "Active",
  },
  {
    id: 2,
    name: "Camera 2",
    health: "Good",
    location: "Los Angeles, CA",
    recorder: "LA Recorder",
    tasks: "5 Tasks",
    status: "Active",
  },
  {
    id: 3,
    name: "Camera 3",
    health: "Poor",
    location: "Chicago, IL",
    recorder: "Chicago Recorder",
    tasks: "2 Tasks",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Camera 4",
    health: "Good",
    location: "Miami, FL",
    recorder: "Miami Recorder",
    tasks: "N/A",
    status: "Active",
  },
  {
    id: 5,
    name: "Camera 5",
    health: "Fair",
    location: "San Francisco, CA",
    recorder: "SF Recorder",
    tasks: "4 Tasks",
    status: "Inactive",
  },
  {
    id: 6,
    name: "Camera 6",
    health: "Good",
    location: "Seattle, WA",
    recorder: "Seattle Recorder",
    tasks: "2 Tasks",
    status: "Active",
  },
  {
    id: 7,
    name: "Camera 7",
    health: "Poor",
    location: "Boston, MA",
    recorder: "Boston Recorder",
    tasks: "N/A",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Camera 8",
    health: "Fair",
    location: "Houston, TX",
    recorder: "Houston Recorder",
    tasks: "3 Tasks",
    status: "Active",
  },
  {
    id: 9,
    name: "Camera 9",
    health: "Good",
    location: "Denver, CO",
    recorder: "Denver Recorder",
    tasks: "1 Task",
    status: "Active",
  },
  {
    id: 10,
    name: "Camera 10",
    health: "Good",
    location: "Phoenix, AZ",
    recorder: "Phoenix Recorder",
    tasks: "5 Tasks",
    status: "Inactive",
  },
  {
    id: 11,
    name: "Camera 11",
    health: "Poor",
    location: "Orlando, FL",
    recorder: "Orlando Recorder",
    tasks: "2 Tasks",
    status: "Active",
  },
  {
    id: 12,
    name: "Camera 12",
    health: "Fair",
    location: "Austin, TX",
    recorder: "Austin Recorder",
    tasks: "N/A",
    status: "Active",
  },
  {
    id: 13,
    name: "Camera 13",
    health: "Good",
    location: "Las Vegas, NV",
    recorder: "Vegas Recorder",
    tasks: "4 Tasks",
    status: "Inactive",
  },
  {
    id: 14,
    name: "Camera 14",
    health: "Poor",
    location: "Atlanta, GA",
    recorder: "Atlanta Recorder",
    tasks: "N/A",
    status: "Inactive",
  },
  {
    id: 15,
    name: "Camera 15",
    health: "Good",
    location: "Charlotte, NC",
    recorder: "Charlotte Recorder",
    tasks: "2 Tasks",
    status: "Active",
  },
  {
    id: 16,
    name: "Camera 16",
    health: "Fair",
    location: "Detroit, MI",
    recorder: "Detroit Recorder",
    tasks: "3 Tasks",
    status: "Inactive",
  },
  {
    id: 17,
    name: "Camera 17",
    health: "Good",
    location: "Philadelphia, PA",
    recorder: "Philly Recorder",
    tasks: "N/A",
    status: "Active",
  },
  {
    id: 18,
    name: "Camera 18",
    health: "Poor",
    location: "San Diego, CA",
    recorder: "SD Recorder",
    tasks: "1 Task",
    status: "Inactive",
  },
  {
    id: 19,
    name: "Camera 19",
    health: "Fair",
    location: "Portland, OR",
    recorder: "Portland Recorder",
    tasks: "3 Tasks",
    status: "Active",
  },
  {
    id: 20,
    name: "Camera 20",
    health: "Good",
    location: "Dallas, TX",
    recorder: "Dallas Recorder",
    tasks: "5 Tasks",
    status: "Inactive",
  },
];

export default cameraData;
